"use client";
import { useState } from "react";
import { Ambulance, Route, Send } from "lucide-react";
import { Shell } from "@/components/Shell";
import { MetricCard, PageHeader, Panel, StatusBadge } from "@/components/operations";
import { triggerEmergencyCorridor } from "@/lib/api";
const intersections = ["J01 · Malviya Nagar", "J02 · Panch Batti", "J03 · Ajmer Road", "J04 · SMS Hospital Road", "J05 · SMS Hospital"];
export default function GreenCorridorsPage() {
 const [active,setActive]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("Demo/simulation view. Live activation is available through the existing API.");
 async function activate(){setBusy(true);try{const response=await triggerEmergencyCorridor("AMB-007","SMS Hospital, Jaipur");setActive(true);setMessage(`Live API activated corridor${response.signalsOptimized?` with ${response.signalsOptimized} optimized signals`:""}.`);}catch{setActive(true);setMessage("Simulation corridor activated locally because the live API is unavailable.");}finally{setBusy(false);}}
 return <Shell><main className="ops-page"><PageHeader index="04" title="Green corridors" subtitle="Multi-intersection priority routes for any authorized traffic operation" actions={<button className="ops-button" disabled={busy} onClick={activate}><Send size={13}/>{busy?"Activating…":"Activate corridor"}</button>}/><div className="ops-grid"><MetricCard label="Active corridors" value={active?1:0} note="Demo / simulation state"/><MetricCard label="Intersections in route" value="5" note="GC-007 coordinated plan"/><MetricCard label="Current route state" value={active?"Green":"Standby"} tone={active?"green":"plain"} note="Adaptive traffic control"/><MetricCard label="Priority class" value="Authorized" tone="plain" note="Emergency is one use case"/></div><div className="ops-layout"><Panel title="GC-007 · City coordination route" subtitle="Demonstration corridor; verify operator authorization before live use"><div className="ops-callout">{message}</div><ol className="corridor-timeline" style={{marginTop:14}}>{intersections.map((node,index)=><li key={node} className={!active&&index>0?"pending":""}><b>{node.split(" · ")[0]}</b><span>{node.split(" · ")[1]}</span><em>{active?index<4?"Green":"Approaching":"Standby"}</em></li>)}</ol><button className="ops-button danger" style={{marginTop:12}} onClick={()=>{setActive(false);setMessage("Corridor placed in standby. Signals continue under adaptive local control.");}}>End corridor</button></Panel><Panel title="Route context" subtitle="Connected junction sequence"><div className="route-map route-map-compact"><div className="map-grid"/><svg viewBox="0 0 300 180"><path className="route-glow" d="M38 37 L84 65 L133 48 L176 91 L224 111 L259 145"/>{[[38,37],[84,65],[133,48],[176,91],[224,111],[259,145]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="7"/><circle className="node-core" cx={x} cy={y} r="3"/></g>)}</svg></div><div className="ops-list" style={{marginTop:12}}><div className="ops-list-item"><div><h3><Ambulance size={14}/> Priority vehicle integration</h3><p>Uses the existing emergency corridor API when a priority vehicle is authorized.</p></div><StatusBadge tone="amber">Demo</StatusBadge></div><div className="ops-list-item"><div><h3><Route size={14}/> General orchestration</h3><p>The same corridor planner can prioritize approved public-safety, transit, or incident response operations.</p></div><StatusBadge>Connected</StatusBadge></div></div></Panel></div></main></Shell>;
}
