"use client";
/* eslint-disable @typescript-eslint/no-unused-vars */
import { useEffect, useState } from "react";
import { Cpu, Radio, RefreshCw, Wifi } from "lucide-react";
import { Shell } from "@/components/Shell";
import { MetricCard, Meter, PageHeader, Panel, StatusBadge } from "@/components/operations";
import { fetchSignals, type Signal } from "@/lib/api";
const fallback: Signal[]=[{id:"GF-EDGE-J01",name:"Malviya Nagar",status:"green",traffic_load:42,lat:0,lng:0},{id:"GF-EDGE-J02",name:"Panch Batti",status:"green",traffic_load:18,lat:0,lng:0},{id:"GF-EDGE-J03",name:"Ajmer Road",status:"yellow",traffic_load:82,lat:0,lng:0},{id:"GF-EDGE-J04",name:"SMS Hospital Rd",status:"green",traffic_load:67,lat:0,lng:0}];
export default function EdgeNetworkPage(){const[nodes,setNodes]=useState(fallback);const[live,setLive]=useState(false);useEffect(()=>{fetchSignals().then(data=>{if(data.length){setNodes(data.map((s,i)=>({...s,id:`GF-EDGE-${s.id||String(i+1).padStart(3,"0")}`})));setLive(true);}}).catch(()=>undefined)},[]);return <Shell><main className="ops-page"><PageHeader index="07" title="IoT Traffic Network" subtitle="Edge device observability, connectivity, and traffic infrastructure health" actions={<button className="ops-button" onClick={()=>window.location.reload()}><RefreshCw size={13}/>Refresh telemetry</button>}/><div className="ops-grid"><MetricCard label="Registered nodes" value={nodes.length} note={live?"Mapped from live signal API":"Simulation mapping"}/><MetricCard label="Node availability" value={`${nodes.length}/${nodes.length}`} note="Current browser session"/><MetricCard label="Connectivity" value="Connected" tone="green" note="WebSocket-capable architecture"/><MetricCard label="Attention needed" value={nodes.filter(n=>n.traffic_load>75).length} tone="amber" note="High-load junctions"/></div><div className="ops-layout"><Panel title="Device telemetry" subtitle="Signal API is used as the available infrastructure source" className="overflow"><table className="ops-table"><thead><tr><th>IoT node</th><th>Location</th><th>Traffic load</th><th>Link health</th><th>State</th></tr></thead><tbody>{nodes.map((node,i)=>{const load=Math.round(node.traffic_load);const attention=load>75;return <tr key={node.id}><td><strong><Cpu size={12}/> {node.id}</strong><br/><span className="demo-label">{live?"Live infrastructure mapping":"Demo telemetry"}</span></td><td>{node.name}</td><td><div style={{minWidth:100}}><Meter value={load} tone={attention?"amber":"green"}/><span className="demo-label">{load}% sensor load</span></div></td><td><span className="demo-label"><Wifi size={11}/> {attention?"72":"96"}% link</span></td><td><StatusBadge tone={attention?"amber":"green"}>{attention?"Monitor":"Online"}</StatusBadge></td></tr>})}</tbody></table></Panel><Panel title="Network topology" subtitle="Illustrative device relationship"><div className="network-graphic"><svg viewBox="0 0 160 170"><path d="M25 25L70 10L132 25L110 65L145 95L96 120L45 146L20 100L48 74Z"/><path d="M25 25L48 74L20 100M70 10L110 65L96 120M132 25L145 95M48 74L110 65M20 100L45 146L96 120M110 65L145 95"/>{[[25,25],[70,10],[132,25],[110,65],[145,95],[96,120],[45,146],[20,100],[48,74]].map(([cx,cy],i)=><circle key={i} cx={cx} cy={cy} r="6" className={i===3?"amber":"green"}/>)}</svg></div><div className="ops-callout"><b><Radio size={13}/> Connected infrastructure.</b> Device status is shown as simulation telemetry when a dedicated node service is not configured; it does not replace backend APIs.</div></Panel></div></main></Shell>}
