"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Ambulance, BrainCircuit, ChevronRight, Cpu, Radio, Sparkles, X } from "lucide-react";
import { Shell } from "@/components/Shell";
import { fetchDashboardMetrics, fetchSignals, triggerEmergencyCorridor, type DashboardMetrics, type Signal as TrafficSignal } from "@/lib/api";

const fallbackMetrics: DashboardMetrics = { trafficFlow: 74, vehiclesPerMinute: 428, avgWait: 41, activeSignals: 24, emergencyVehiclesActive: 7, aiPredictionConfidence: 92 };
const corridorNodes = ["J01", "J02", "J03", "J04", "J05"];
const incidents = [["AMB-007", "MI Road, Jaipur → SMS Hospital", "04:21", "03:53", "critical"], ["AMB-008", "Mansarovar → Fortis Hospital", "06:12", "02:41", "active"], ["AMB-009", "Malviya Nagar → SMS Hospital", "05:43", "02:17", "active"], ["AMB-010", "Jagatpura → EHCC Hospital", "07:11", "01:32", "active"]] as const;

export default function DashboardPage() {
  const [metrics, setMetrics] = useState(fallbackMetrics); const [signals, setSignals] = useState<TrafficSignal[]>([]); const [selectedIncident, setSelectedIncident] = useState("AMB-007"); const [activeTab, setActiveTab] = useState("All (7)"); const [corridorActive, setCorridorActive] = useState(true); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { Promise.allSettled([fetchDashboardMetrics(), fetchSignals()]).then(([dashboard, signalData]) => { if (dashboard.status === "fulfilled") setMetrics(dashboard.value); if (signalData.status === "fulfilled") setSignals(signalData.value); }); }, []);
  const flow = Math.min(100, Math.max(0, metrics.trafficFlow)); const synced = signals.length ? signals.filter((signal) => ["green", "priority", "green_corridor"].includes(signal.status)).length : 24; const currentIncident = useMemo(() => incidents.find(([id]) => id === selectedIncident) ?? incidents[0], [selectedIncident]);
  async function activateCorridor() { setBusy(true); setNotice(null); try { const result = await triggerEmergencyCorridor(selectedIncident, "SMS Hospital, Jaipur"); setCorridorActive(true); setNotice(`Corridor activated${result.signalsOptimized ? ` · ${result.signalsOptimized} signals optimized` : ""}`); } catch { setCorridorActive(true); setNotice("Demo corridor activated locally. Live service will reconnect automatically."); } finally { setBusy(false); } }
  return <Shell><div className="command-center">
    {notice && <div className="command-notice"><Sparkles size={14}/>{notice}<button onClick={() => setNotice(null)} aria-label="Dismiss notification"><X size={14}/></button></div>}
    <section className="command-grid command-grid-primary">
      <Panel title="1. Overview" subtitle="Real-time command center"><div className="metric-strip"><Metric label="Active incidents" value={metrics.emergencyVehiclesActive}/><Metric label="Ambulances" value="14" tone="amber"/><Metric label="Green corridors" value={corridorActive ? "4" : "3"} tone="green"/><Metric label="Signals synced" value={synced} tone="green"/></div><RouteMap compact/><div className="overview-kpis"><Kpi label="Average ETA reduction" value="−48%" note="vs normal"/><Kpi label="Average response time" value="04:21" note="min"/><Kpi label="Traffic flow improvement" value={`+${Math.max(8, Math.round(flow / 3))}%`} note="today"/></div></Panel>
      <Panel title="2. Live operations" subtitle="Monitor all active incidents"><div className="tab-row">{["All (7)", "Critical (2)", "Active (4)", "Resolved (1)"].map((tab) => <button key={tab} onClick={() => setActiveTab(tab)} className={activeTab === tab ? "is-active" : ""}>{tab}</button>)}</div><div className="incident-list">{incidents.map(([id, route, eta, saved, status]) => <button key={id} onClick={() => setSelectedIncident(id)} className={`incident-card ${selectedIncident === id ? "is-selected" : ""}`}><span><strong>{id}</strong><small>{route}</small><em>ETA <b>{eta}</b> <i>Saved {saved}</i></em></span><Badge tone={status === "critical" ? "red" : "green"}>{status}</Badge></button>)}</div><a className="panel-link" href="/live-operations">View all incidents <ChevronRight size={14}/></a></Panel>
      <Panel title="3. Emergency response" subtitle="Manage emergency vehicle"><div className="vehicle-head"><div><b>{currentIncident[0]}</b><small>Emergency vehicle</small></div><Badge tone="red">Critical</Badge><Badge tone="green">Live</Badge></div><div className="emergency-map"><div className="route-detail"><small>From</small><b>MI Road, Jaipur</b><small>To</small><b>SMS Hospital, Jaipur</b><span><strong>7.2 km</strong><strong>08:14 min</strong></span></div><RouteMap/></div><div className="eta-bar"><span>Time saved</span><strong>03:53 min</strong><b>−48%</b></div><button className="action-button" onClick={activateCorridor} disabled={busy}>{busy ? "Activating…" : corridorActive ? "Manage corridor" : "Activate corridor"}</button><button className="danger-button" onClick={() => { setCorridorActive(false); setNotice("Emergency corridor ended. Signals returned to adaptive control."); }}>End emergency</button></Panel>
      <Panel title="4. Green corridors" subtitle="Active corridor management"><div className="corridor-heading"><span>Corridor ID</span><strong>GC-007</strong><Badge tone="green">{corridorActive ? "Active" : "Standby"}</Badge></div><small className="started">Started at 14:28:15</small><ol className="corridor-timeline">{corridorNodes.map((node, index) => <li key={node} className={index > 2 && !corridorActive ? "pending" : ""}><b>{node}</b><span>{["Malviya Nagar", "Panch Batti", "Ajmer Road", "SMS Hospital Rd", "SMS Hospital"][index]}</span><em>{index < 3 ? "Green" : index === 3 ? "Preparing" : "Upcoming"}</em></li>)}</ol><button className="danger-button" onClick={() => setCorridorActive(false)}>End corridor</button></Panel>
      <Panel title="5. Signal synchronization" subtitle="Traffic signal control"><div className="signal-status"><b>J03</b><span>Ajmer Road</span><Badge tone="green">Synced</Badge></div><Intersection/><div className="phase-row"><span><small>Current phase</small><strong>Green</strong></span><span><small>Time left</small><strong>28 sec</strong></span></div><div className="phase-row muted"><span><small>Next phase</small><strong>Yellow</strong></span><span><small>Then</small><strong>Red · 30 sec</strong></span></div><button className="outline-button" onClick={() => setNotice("Manual signal override queued for operator confirmation.")}>Manual override</button></Panel>
    </section>
    <section className="command-grid command-grid-secondary">
      <Panel title="6. Traffic network" subtitle="Road network monitoring"><div className="network-content"><RoadList/><NetworkGraphic/></div><Legend items={[["#31d77b", "Low"], ["#d7a93e", "Moderate"], ["#e95b5b", "High"], ["#ff4d4d", "Severe"]]}/></Panel>
      <Panel title="7. Edge network" subtitle="IoT edge monitoring"><div className="node-stats"><Metric label="Total nodes" value="12"/><Metric label="Online" value="12"/><Metric label="Warning" value="0" tone="amber"/><Metric label="Offline" value="0" tone="red"/></div><div className="edge-list">{["GF-EDGE-J01", "GF-EDGE-J02", "GF-EDGE-J03", "GF-EDGE-J04"].map((node, index) => <div key={node}><Cpu size={12}/><b>{node}</b><span>{["Malviya Nagar", "Panch Batti", "Ajmer Road", "SMS Hospital Rd"][index]}</span><em>Online · 2s</em></div>)}</div><a className="panel-link" href="/edge-network">View network topology <ChevronRight size={14}/></a></Panel>
      <Panel title="8. Lane management" subtitle="Dynamic lane guidance"><LaneGraphic/><div className="lane-table">{[["Lane 1", "82%", "18 km/h", "High"], ["Lane 2", "31%", "46 km/h", "Clear"], ["Lane 3", "67%", "24 km/h", "Moderate"]].map(([lane, density, speed, status]) => <div key={lane}><b>{lane}</b><span>{density}</span><span>{speed}</span><em className={status === "High" ? "danger" : ""}>{status}</em></div>)}</div><div className="recommendation">Recommended emergency lane <b>Lane 2</b></div></Panel>
      <Panel title="9. Traffic insights" subtitle="AI-powered insights & recommendations"><div className="insight"><BrainCircuit/><div><small>Current insight</small><p>High congestion predicted on Ajmer Road in next 15 minutes.</p></div></div><div className="insight compact"><Radio/><div><small>Recommended action</small><p>Extend green phase at J03 by 12 seconds.</p></div></div><div className="improvement"><span>Expected improvement</span><b>+24% traffic flow</b><strong>−18% delay</strong></div><button className="outline-button" onClick={() => setNotice("AI recommendation applied to J03 signal plan.")}>Apply recommendation</button></Panel>
      <Panel title="10. Analytics" subtitle="Performance & impact analytics"><div className="analytics-stats"><Kpi label="Emergencies assisted" value="14" note="+27%"/><Kpi label="Avg ETA reduction" value="48%" note="+9%"/><Kpi label="Green corridors" value="4" note="+33%"/></div><div className="chart"><svg viewBox="0 0 320 90" preserveAspectRatio="none"><path d="M0,65 C18,60 24,70 44,56 S72,43 87,56 S108,21 132,14 S150,60 173,59 S198,47 214,62 S236,73 254,48 S279,47 297,55 S309,41 320,43" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M0,65 C18,60 24,70 44,56 S72,43 87,56 S108,21 132,14 S150,60 173,59 S198,47 214,62 S236,73 254,48 S279,47 297,55 S309,41 320,43 V90 H0Z" fill="url(#area)"/><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#31d77b" stopOpacity=".28"/><stop offset="1" stopColor="#31d77b" stopOpacity="0"/></linearGradient></defs></svg></div></Panel>
    </section>
  </div></Shell>;
}

function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <article className="command-panel"><header><div><h2>{title}</h2><p>{subtitle}</p></div><span className="panel-corner"/></header>{children}</article>; }
function Metric({ label, value, tone = "" }: { label: string; value: string | number; tone?: string }) { return <div className="metric"><small>{label}</small><strong className={tone}>{value}</strong></div>; }
function Kpi({ label, value, note }: { label: string; value: string; note: string }) { return <div className="kpi"><small>{label}</small><strong>{value}</strong><em>{note}</em></div>; }
function Badge({ tone, children }: { tone: "green" | "amber" | "red"; children: ReactNode }) { return <span className={`badge badge-${tone}`}>{children}</span>; }
function RouteMap({ compact = false }: { compact?: boolean }) { return <div className={`route-map ${compact ? "route-map-compact" : ""}`}><div className="map-grid"/><svg viewBox="0 0 300 180" preserveAspectRatio="none"><path d="M55 35 L102 56 L142 51 L180 86 L225 102 L250 145"/><path className="route-glow" d="M55 35 L102 56 L142 51 L180 86 L225 102 L250 145"/>{[[55,35],[102,56],[142,51],[180,86],[225,102],[250,145]].map(([x,y], i) => <g key={i}><circle cx={x} cy={y} r="7"/><circle className="node-core" cx={x} cy={y} r="3"/></g>)}<text x="37" y="25">AMB</text><text x="239" y="165">H</text></svg><div className="map-legend"><span><i/> Ambulance</span><span><i/> Green corridor</span><span><i/> Traffic congestion</span></div></div>; }
function Intersection() { return <div className="intersection"><span className="road horizontal"/><span className="road vertical"/><span className="car car-a"/><span className="car car-b"/><span className="car car-c"/><span className="light light-one"/><span className="light light-two"/></div>; }
function RoadList() { return <div className="road-list">{[["J01","Malviya Nagar","42 km/h","low"],["J02","Panch Batti","18 km/h","moderate"],["J03","Ajmer Road","15 km/h","high"],["J04","Raja Park","35 km/h","moderate"],["J05","NH Road","52 km/h","low"]].map(([id, name, speed, level]) => <div key={id}><b>{id}</b><span>{name}</span><em className={level}>{level}</em><small>{speed}</small></div>)}</div>; }
function NetworkGraphic() { return <div className="network-graphic"><svg viewBox="0 0 160 170"><path d="M25 25L70 10L132 25L110 65L145 95L96 120L45 146L20 100L48 74Z"/><path d="M25 25L48 74L20 100M70 10L110 65L96 120M132 25L145 95M48 74L110 65M20 100L45 146L96 120M110 65L145 95"/>{[[25,25],[70,10],[132,25],[110,65],[145,95],[96,120],[45,146],[20,100],[48,74]].map(([cx,cy], i)=><circle key={i} cx={cx} cy={cy} r="6" className={i===7 ? "red" : i===3 || i===8 ? "amber" : "green"}/>)}</svg></div>; }
function Legend({ items }: { items: [string, string][] }) { return <div className="legend">{items.map(([color, label]) => <span key={label}><i style={{ backgroundColor: color }}/>{label}</span>)}</div>; }
function LaneGraphic() { return <div className="lane-graphic"><span/><span/><span/><i className="ambulance-icon"><Ambulance size={18}/></i><i className="mini-car a"/><i className="mini-car b"/><i className="mini-car c"/></div>; }
